#!/bin/bash

masses=(
	800
	1000
	1200
	1400
	1600
)

xangles=(
	120
	130
	140
	150
)

n_events=400000
#n_events=100000
#n_events=4000

save_ntuples="False"

#----------------------------------------------------------------------------------------------------

function RunOne()
{
	dir="m_X_$mass/xangle_$xangle"
	eos_dir="/eos/totem/user/j/jkaspar/PPXZ/m_X_$mass/xangle_$xangle"
	echo $dir

	mkdir -p "$dir"
	eos mkdir -p "$eos_dir"

	cat "template_cfg.py"|sed "\
			s|\$mass|$mass|g;\
			s|\$xangle|$xangle|g;\
			s|\$n_events|$n_events|g;\
			s|\$eos_dir|$eos_dir|g;\
			s|\$save_ntuples|$save_ntuples|g;\
		" > "$dir/cfg.py"

	cd "$dir"

	cmsRun "cfg.py" &> "log" &

	cd - &> /dev/null
}

#----------------------------------------------------------------------------------------------------

for mass in ${masses[*]}
do
	for xangle in ${xangles[*]}
	do
		RunOne
	done
done
