#!/bin/bash

function SubmitOneDir()
{
	local tag="$1"
	local selection="$2"
	local top_dir="$3"

	local buf="$tag"

	fill=${buf#fill}
	fill=${fill%%_*}

	buf=${buf#*_}
	xangle=${buf%%_*}
	xangle=${xangle#xangle}

	buf=${buf#*_}
	stream=${buf%%.*}

	echo "* $fill, $xangle, $stream"

	# get input
	input=""
	for f in `eos ls "$eos_dir"|grep $tag|grep "$selection"|grep .root`
	do
		if [ -n "$input" ]
		then
			input="$input\n"
		fi

		input="${input}process.source.fileNames.append(\"root://eostotem.cern.ch/${eos_dir}/${f}\")"
	done

	for alignment in ${alignments[*]}
	do
		echo "  $alignment"

		# make work directory
		subdir="fill_$fill/xangle_$xangle/$stream/alignment_$alignment"
		dir="$top_dir/$subdir"
		mkdir -p "$dir"
		rm -rf "$dir/output.root"

		full_dir="`pwd -P`/$dir"

		# make config with input files
		cat "template_cfg.py" | sed -e "\
				s|\$input|$input|g;\
				s|\$fill|$fill|g;\
				s|\$xangle|$xangle|g;\
				s|\$alignment|$alignment|g;\
				s|\$output|output.root|g;\
			" > "$dir/cfg.py"

		# make job
		cat "template_job" | sed "\
				s|\$job_dir|$full_dir|g;\
				s|\$CMSSW_BASE|$CMSSW_BASE|g;\
			" > "$dir/job"
		chmod u+x "$dir/job"

		# add submission line
		(
			echo ""
			echo "dir=$subdir"
			echo "queue"
		) >> "$condor_file_sub"
	done
}

#----------------------------------------------------------------------------------------------------

function SubmitOneGroup()
{
	local selection="$1"
	local top_dir="$2"

	mkdir -p "$top_dir"

	condor_file_sub="$top_dir/condor_${selection}.sub"

	# initiate submission script
	(
		local base_dir_full="$(pwd)/$top_dir"
		echo "executable = $base_dir_full/\$(dir)/job"
		echo "arguments = \$(ClusterId) \$(ProcId) \\\"\$(dir)\\\""
		echo "output = $base_dir_full/\$(dir)/out"
		echo "error = $base_dir_full/\$(dir)/err"
		echo "log = $base_dir_full/condor_${selection}.log"

		echo "+MaxRuntime = 7200"
		#echo "+JobBatchName = \"$job_name\""
		#echo "requirements = (OpSysAndVer =?= \"SLCern6\")"

	) > "$condor_file_sub"

	# loop over input files
	for tag in `eos ls "$eos_dir"|grep "$selection"|grep DoubleEG|grep .root|uniq`
	do
		SubmitOneDir "$tag" "$selection" "$top_dir"
	done

	# submit
	condor_submit "$condor_file_sub"
}

#----------------------------------------------------------------------------------------------------

eos_dir="/eos/totem/data/ctpps/reconstruction/2017/postTS2_alignment_data/version5"

alignments=(
	"2018_10_25.5"
)

SubmitOneGroup "xangle140" "data_eos/"
